# Project Information
site_name: f61d
site_description: writeups of f61d team
site_author: f61d
site_url: https://f61d.github.io/

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true

# Repository
repo_name: 'f61d/f61d.github.io'
repo_url: 'https://github.com/f61d/f61d.github.io/'
edit_uri: 'blob/dev/docs/'

# Copyright
copyright: 'Copyright &copy; f61d team'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
- home: index.md
- web:
  - home: web/index.md
  - CommandInjection:
    - hitcon2019-virtual-public-network: web/CommandInjection/hitcon2019-virtual-public-network.md
  - PHP:
    - WHUCTF-EasyPHP: web/PHP/WHUCTF-EasyPHP.md
    - ichunqiuCTF_easyphp: web/PHP/ichunqiuCTF_easyphp.md
    - ictf_best_language1: web/PHP/ictf_best_language1.md
  - SQLi:
    - RootersCTF-Babyweb: web/SQLi/RootersCTF-Babyweb.md
  - Session Bypass:
    - hackergame2019-django: web/Session Bypass/hackergame2019-django.md
  - FileUpload:
    - RoarCTF-simple_upload: web/FileUpload/RoarCTF-simple_upload.md
  - JavaScript_prototype_chain_pollution:
    - car_repair: web/JavaScript_prototype_chain_pollution/car_repair.md
- pwn:
  - home: pwn/index.md
  - Heap:
    - LazyHouse: pwn/Heap/LazyHouse.md
    - 4-ReeHY-main: pwn/Heap/4-ReeHY-main.md
  - VMEscape:
    - BabyQemu: pwn/VMEscape/BabyQemu.md
    - scvm: pwn/VMEscape/scvm.md
  - Windows:
    - BabyStack: pwn/Windows/BabyStack.md
  - Stackoverflow:
    - brop: pwn/Stackoverflow/brop.md
    - level5: pwn/Stackoverflow/level5.md
    - 100levels: pwn/Stackoverflow/100levels.md
    - Story: pwn/Stackoverflow/Story.md
- crypto:
  - home: crypto/index.md
  - RSA:
    - roarctf_rsa: crypto/RSA/roarctf_rsa.md
    - roXen: crypto/RSA/roXen.md
  - Stream_Cipher:
    - Hacklu2019_COBOL_OTP: crypto/Stream_Cipher/Hacklu2019_COBOL_OTP.md
- reverse:
  - home: reverse/index.md
- misc:
  - home: misc/index.md
  - blockchain:
    - RoarCTF2019_CoinFlip: misc/blockchain/RoarCTF2019_CoinFlip.md
    - Hackergame2019_JCBank: misc/blockchain/Hackergame2019_JCBank.md
  - forensic:
    - Traffic_Analysis: misc/forensic/Traffic_Analysis.md
- backup:
  - "gitpage\u91C7\u5751": backup/gitpage_fuck.md
