# Project Information
site_name: f61d
site_description: writeups of f61d team
site_author: f61d
site_url: https://f61d.github.io/

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true

# Repository
repo_name: 'f61d/f61d.github.io'
repo_url: 'https://github.com/f61d/f61d.github.io/'
edit_uri: 'blob/dev/docs/'

# Copyright
copyright: 'Copyright &copy; f61d team'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Contents
nav:
    - home: index.md
    - ctf writeups:
        - linux内核基础: kernel/linux_kernel_base.md
    - backup:
        - gitpage采坑: backup/gitpage_fuck.md